#!/bin/csh

#
# parser/lib/plus --
#
#	This shell script C++-ifies YACC and LEX output
#
# Copyright (c) 1993-1997 Olav Schettler
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
# $Id: plus,v 1.1 1995/10/25 20:09:25 olav Exp $
#--------------------------------------------------------------------------
# $Log: plus,v $
# Revision 1.1  1995/10/25  20:09:25  olav
# 1
#
#

cat > /tmp/plus.$$ <<.EOF.
s/$1error/$1Tree->error/g
.EOF.
sed -f /tmp/plus.$$ $2 > $3 && rm $2
rm /tmp/plus.$$
