#
# ibe/Makefile --
#
#	This Makefile describes the construction process for
#	the example language processor 'ibe', 
#	illustrating the (is,begin,end)-problem
#
# Copyright (c) 1993-1997 Olav Schettler
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
# $Id: Makefile,v 1.1 1995/10/25 20:09:23 olav Exp $
#--------------------------------------------------------------------------
# $Log: Makefile,v $
# Revision 1.1  1995/10/25  20:09:23  olav
# 1
#
#


GRAMMAR = ibe

include ../simple.mk
