#!/bin/csh
#
# bind/cbind --
#
#	Csh driver of cbind, the wrapper generator used to
#	generate shared libraries for cocos class definitions
#
# Copyright (c) 1993-1997 Olav Schettler
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
# $Id: cbind,v 1.1 1995/10/25 20:09:22 olav Exp $
#--------------------------------------------------------------------------
# $Log: cbind,v $
# Revision 1.1  1995/10/25  20:09:22  olav
# 1
#
#

setenv dir $HOME/cocos/src/bind
$dir/x <<.EOF.
source $dir/bind.tcl
cocos_bind $1 $2
.EOF.
